# Generated by Django 5.0 on 2024-06-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCIP_APP', '0006_remove_userprofile_country_remove_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
